### ISSUE TITLE
I tried to identify the .Net PE file, but there was an error.

### ISSUE THREAD

**Issue by Aixic-Love** [saferwall/pe#1]
this is https://github.com/pandasec888/taowu-cobalt-strike/blob/master/script/SharpBypassUAC.exe

![image](https://user-images.githubusercontent.com/50495439/109836583-42e61d80-7c7f-11eb-8b85-f603a0df8ea6.png)

I just want to get his moduleName..
Used to label the file name.

```go
package main

import (
    "fmt"
    peparser "github.com/saferwall/pe"
)

func main() {
    filename:=`C:\Users\a3ro\Desktop\6FAD3A96FE407982818CE27F73C78B8AC3B0902BD85F104DC85EEF092F4186DE.exe`
    pe, err := peparser.New(filename, nil)
    if err != nil {
        fmt.Printf("Error while opening file: %s, reason: %s", filename, err)
    }

    err = pe.Parse()
    if err != nil {
        fmt.Printf("Error while opening file: %s, reason: %s", filename, err)
    }
}
```

**Comment by LordNoteworthy** [comment]
That's right ! Thanks @Aixic-Love for reporting this. I just fixed it.

By `moduleName`, you mean this:

![image](https://user-images.githubusercontent.com/5129564/109954424-2d302280-7c96-11eb-8536-f839f5b801ea.png)

**Comment by actuallyachraf** [comment]
@Aixic-Love if the last commit by @LordNoteworthy fixed your issue please ACK.
Thank you for helping this package become better !

**Comment by actuallyachraf** [comment]
Marked as closed.

**Comment by LordNoteworthy** [comment]
You can try this code:

```golang
if modTable, ok := pe.CLR.MetadataTables[peparser.Module]; ok {
	if modTable.Content != nil {
		modTableRow := modTable.Content.(peparser.ModuleTableRow)
		modName := pe.GetStringFromData(modTableRow.Name, pe.CLR.MetadataStreams["#Strings"])
		moduleName := string(modName)
		log.Println(moduleName)
	}
}
```

It prints:
```
2021/03/08 11:50:01 SharpBypassUAC.exe
```

If you need something else, feel free to re-open the issue.

**Comment by Aixic-Love** [comment]
I want to pass in byte[] file for memory scanning..
