### ISSUE TITLE
Documentation uses method pe.PrettyMachineType that doesn't exist

### ISSUE THREAD

**Issue by edeca** [saferwall/pe#102]
The documentation in `README.md` mentions `pe.PrettyMachineType()` which doesn't seem to exist. The relevant line is:

    fmt.Printf("Machine is: 0x%x, Meaning: %s\n", pe.NtHeader.FileHeader.Machine, pe.PrettyMachineType())

Using this code as shown produces the error:

    .\main.go:24:83: pe.PrettyMachineType undefined (type *pe.File has no field or method PrettyMachineType)

**Comment by LordNoteworthy** [comment]
You should use `pe.NtHeader.FileHeader.Machine.String()`. More go idiomatic, I changed all *Pretty() to String()
