### ISSUE TITLE
Make get_data / get_rva_from_offset public

### ISSUE THREAD

**Issue by Kwansy98** [saferwall/pe#16]

**Comment by Kwansy98** [comment]
I want to access File.data but it's private

**Comment by LordNoteworthy** [comment]
Yes, I will make them public, they should be. I will make a PR tonight.

**Comment by Kwansy98** [comment]
Thank you LordNoteworthy :)

**Comment by LordNoteworthy** [comment]
v1.1.1 should have this fixed, you can upgrade the pkg and check. Thanks :+1:
