### ISSUE TITLE
Allow access to the raw certificates content

### ISSUE THREAD

**Issue by epsleq0** [saferwall/pe#21]
`saferwall/pe` provides access to the [parsed certificates](https://github.com/saferwall/pe/blob/00ebfd451e6ce4e9e69b6b6aa68cfe7d9df368a4/security.go#L232). However, neither `saferwall/pe` nor the used `pkcs7` module allow access the to the raw certificates content.

I would like to read the raw certificates content using `saferwall/pe`, to persist and analyze it externally.

**Comment by LordNoteworthy** [comment]
Hello @epsleq0 

I believe this is available to you.

```go
// Certificate directory.
type Certificate struct {
	Header   WinCertificate
	Content  *pkcs7.PKCS7 `json:"-"` <---- This field ?
	Info     CertInfo
	Verified bool
}
```

**Comment by epsleq0** [comment]
Thanks @LordNoteworthy. AFAICS, `pkcs.PKCS7` is a structure that contains **parsed** information about a DER encoded PKCS7 package. Once parsed, it is not possible to get the input data back there. Of course there is `pkcs7.PKCS7.Content` and `x509.Certificate.Raw` - but this information is not sufficient to reconstruct the full PKCS7 package.
This is not a problem of `pkcs7`, because they only offer parsing.

It would be great if I could get access to the `certContent` that is passed when `pkcs7.Parse` [is called](https://github.com/saferwall/pe/blob/00ebfd451e6ce4e9e69b6b6aa68cfe7d9df368a4/security.go#L233).

**Comment by LordNoteworthy** [comment]
I see what you mean now. Are you satisfied with the patch I applied ?

You can fetch the last tag to test it out.

**Comment by epsleq0** [comment]
Thanks, it works like a charm!
