### ISSUE TITLE
Incorrect check for skipCertVerification in security.go

### ISSUE THREAD

**Issue by edygert** [saferwall/pe#29]
The check on line 302 in security.go should be "if !skipCertVerification" so that VerifyWithChain will be called.

**Comment by LordNoteworthy** [comment]
Hey @edygert 

That's correct 👌 I will fix that today.

**Comment by LordNoteworthy** [comment]
Fixed in d12bac5b8c708cf4228f3808d001f3d0ffa6fdf7

Thank you !
