### ISSUE TITLE
Inaccurate value of Authentihash

### ISSUE THREAD

**Issue by wanglei-coder** [saferwall/pe#31]
the value of Authentihash is different from virustotal. and Value overflow occurred which cause panic.

**Comment by LordNoteworthy** [comment]
Hello Wanglei,

Can you please provide me with a hash so I can test it.

**Comment by Mamba24L8** [comment]
panic:
filemd5：2c766f87b1fbd4623f8cd3f4d7e4d077；filename: CPU-Z@5893399_91178.exe。
errors:
panic: runtime error: slice bounds out of range [651776:648704]

goroutine 1 [running]:
github.com/saferwall/pe.(*File).Authentihash(0xc0000003c0)
        /home/mamba/go/pkg/mod/github.com/saferwall/pe@v1.2.1/security.go:193 +0x49a
main.main()
        /mnt/c/Users/86187/code/cloud_av/engine/cmd/auth/main.go:21 +0x138
-----------------------------------------------------------------------------------------------------
and some value is incorrect：
md5 :5b7f9a8a54b40f6f082eb6dbc97815ea  
saferwall/pe: 3a7de06d59963b427aeb0092354fd778f6f501ab76440560eb6898b0f1919407 virustotal:fecdc011fcb33c0ee0e2d493060fda809c07de54643c5dddd6171b27838e6f98

**Comment by LordNoteworthy** [comment]
Thanks to @wanglei-coder , this issue is now solved.
