### ISSUE TITLE
`Authentihash` Function doesn't generate valid Authenticode Hashes

### ISSUE THREAD

**Issue by fernandolobato** [saferwall/pe#5]
I was interested in re-creating sbsign tool in golang, the only obstacle is that Authenticode hashes seem to be a headache. I found this library which looks very promising. 

Am pretty sure there's an issue with the `Authentihash` function. I created a digest for a specific file using this library and then created another hash for the same file using: https://git.kernel.org/pub/scm/linux/kernel/git/jejb/sbsigntools.git/tree/src/image.c#n510

I got different values. I'm pretty confident on the result of sbsign, I signed my kernel with that and UEFI secure boot verifies it. I'm sorry I can't provide much more details or logs. I would like to be more helpful than just pointing things out. I thought it was still worth opening this.

Cheers.

**Comment by LordNoteworthy** [comment]
Hello @fernandolobato 

You are right ! good catch. I just released a new tag: v1.0.5, can you give it a quick try ?

Cheers.

**Comment by fernandolobato** [comment]
Hello!

Thank you so much for looking at this, I've tested it against a couple of boot-loaders and it seems perfect. Sorry for the long response, I was out in the mountains. I will close this issue. 

Cheers!
