### ISSUE TITLE
run in goroutine

### ISSUE THREAD

**Issue by maxbad** [saferwall/pe#50]
When the code is executed to print end, the file is still occupied and cannot be deleted
```
func main() {
	var wg sync.WaitGroup
	wg.Add(1)

	go func() {
		filename := "C:\\test.exe"
		pe, err := peparser.New(filename, &peparser.Options{Fast: true})
		if err == nil {
			pe.Close()
		}
		wg.Done()
	}()

	wg.Wait()
	fmt.Println("end")
}

```

**Comment by LordNoteworthy** [comment]
Hello @maxbad 

Which version are you using ?

**Comment by maxbad** [comment]
Windows

**Comment by LordNoteworthy** [comment]
Thanks for reporting the error ! indeed, it looks like during unmapping of memory, it fails during flush memory.

I just released a new tag: 1.3.2, can you give it a try ?

**Comment by maxbad** [comment]
I just tried it and it works fine now, thanks!

**Comment by LordNoteworthy** [comment]
Great ! Thanks a lot for reporting it.
