### ISSUE TITLE
Malware using fake NumberOfSymbols causes OOM during ParseCOFFSymbolTable

### ISSUE THREAD

**Issue by CodingBeard** [saferwall/pe#6]
Hey,

In symbol.go:266 you preallocate a slice with the given value of `pe.NtHeader.FileHeader.NumberOfSymbols`, this can be abused by malware to force an OOM error by providing a fake and absurdly high value. I suggest adding a configurable/sensible limit to prevent this.

I forked and added a hardcoded value for my own use, but a new config option and/or a sensible limit may help others.

Thanks

**Comment by LordNoteworthy** [comment]
Thanks for reporting this, will add a fix today.

Btw, do you have a sha I can add to unit tests ?

**Comment by CodingBeard** [comment]
`SHA256`: 0000e876c5b712b6b7b3ce97f757ddd918fb3dbdc5a3938e850716fbd841309f 
`pe.NtHeader.FileHeader.NumberOfSymbols`: 1564823652
`len(pe.Imports)`: 1

Seems to be on virus total if you can get it from there.

Thanks for the great library.

**Comment by ayfaouzi** [comment]
Thanks a lot for sharing the hash. I added a configurable limit to prevent it. See (daa14e98f4efb3025b190ba7722c256314425fd4)

Thanks again for reporting it !

**Comment by LordNoteworthy** [comment]
I just fixed the issue by adding a configurable limit. See (daa14e98f4efb3025b190ba7722c256314425fd4)

I released a new tag as well. Thanks again for reporting it !
